# Generated by Django 4.1.6 on 2023-03-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='hex',
            field=models.CharField(choices=[('#FFFF0090', 'yellow'), ('#FF000050', 'red'), ('#00FF0090', 'green')], max_length=10, verbose_name='HEX'),
        ),
    ]
