# Generated by Django 4.1.6 on 2023-05-18 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex', models.CharField(choices=[('#FFFF0090', 'yellow'), ('#FF000050', 'red'), ('#00FF0090', 'green')], max_length=10, verbose_name='HEX')),
                ('name', models.CharField(default=None, max_length=40, null=True)),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='ColorPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('high_importance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high', to='register.color')),
                ('low_importance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low', to='register.color')),
                ('medium_importance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medium', to='register.color')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='register.colorpreference'),
        ),
    ]
